theme: jekyll-theme-slate

title: [NLP@CSEBUET]
description: [Natural Language Processing (NLP) at the Department of Computer Science and Engineering (CSE) of Bangladesh University of Engineering and Technology (BUET)]
show_downloads: ["false"]
